import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "../app/components/sidebar/sidebar";
import { Inter } from "next/font/google";
import Header from "../app/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Admin portal",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${inter.className} flex h-screen`}>
        {/* Sidebar */}
        <Sidebar className="w-64 bg-gray-900 text-white h-full" />

        {/* Main Content */}
        <div className="flex flex-col flex-grow h-full">
            <Header className="bg-gray-100 text-black p-4" />
            <div className="flex-grow bg-gray-100 p-4 overflow-auto">
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}

