import "./globals.css";
import Sidebar from "../app/components/sidebar/sidebar";
import { Inter } from "next/font/google";
import Header from "../app/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Admin portal",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${inter.className} flex h-screen`}>
        {/* Sidebar */}
        <div className="h-screen sm:h-auto sm:overflow-y-auto md:h-auto lg:h-full xl:overflow-y-auto">
            <Sidebar/>
        </div>

        {/* Main Content */}
        <div className="flex flex-col flex-grow h-screen overflow-hidden">
            <Header className="bg-gray-100 text-black p-4" />
            <div className="flex-grow bg-gray-100 p-4 overflow-y-auto">
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
