import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "../app/components/sidebar/sidebar";
import {Inter} from "next/font/google";

const inter =Inter({ subsets: ["latin"]});
export const metadata = {
  title: "Admin portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${inter.className} flex`}>
        <Sidebar />
        <div className="flex-grow bg-gray-800">
            {children}
        </div>
        </body>
        </html>
    );
}
